# See http://about.travis-ci.org/docs/user/build-configuration/
# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/766cd1435a839e757239
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script: "sbt clean coverage test"
after_success: "sbt coveralls"